### ISSUE TITLE
Python example: AttributeError: 'RepeatedCompositeFieldContainer' object has no attribute 'data'

### ISSUE THREAD

**Issue by RakibFiha** [infostellarinc/stellarstation-api#249]
Examples of printing-client fails with:

```bash
$ python3 printing-client.py
Traceback (most recent call last):
  File "/Users/mdrakiburrahman/Environments/2.Current_Work/stellarpy/stellarstation-api/examples/python/printing-client/printing-client.py", line 89, in <module>
    run()
  File "/Users/mdrakiburrahman/Environments/2.Current_Work/stellarpy/stellarstation-api/examples/python/printing-client/printing-client.py", line 56, in run
    response.receive_telemetry_response.telemetry.data)[:100])
AttributeError: 'RepeatedCompositeFieldContainer' object has no attribute 'data'
```

Python environment:
```bash
$ python3 -V
Python 3.9.0
```

OS:
```bash
$ uname -ar
Darwin MacBookPro-4.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

requirements.txt
```bash
$ pip3 freeze
cachetools==3.1.0
certifi==2019.3.9
chardet==3.0.4
colorclass==2.2.0
docopt==0.6.2
google-api-core==1.10.0
google-auth==1.23.0
google-cloud-core==0.29.1
google-cloud-storage==1.15.0
google-resumable-media==0.3.2
googleapis-common-protos==1.5.10
grpcio==1.33.2
idna==2.8
protobuf==3.8.0
pyasn1==0.4.5
pyasn1-modules==0.2.5
pytz==2019.1
requests==2.24.0
rsa==4.0
six==1.12.0
stellarstation==0.9.0
urllib3==1.25.11
```

**Comment by danada** [comment]
Hi @RakibFiha , thanks for reporting this. Some of the examples of this repo haven't been updated for a while, so we will look into updating the examples to work with newer versions of the API (see #248).

This particular issue is caused by the [`telemetry`](https://github.com/infostellarinc/stellarstation-api/blob/master/api/src/main/proto/stellarstation/api/v1/stellarstation.proto#L352) field becoming repeated in version [0.9.0](https://github.com/infostellarinc/stellarstation-api/releases/tag/0.9.0). It's possible to fix this by iterating through the repeated `telemetry` field then accessing the `data` field.

In the meantime you should be able to pin the API to version 0.8.0 that still uses non-repeated `telemetry` field.
